export let products = [

    {
        title: "Pachira",
        price: 3000,
        stock: 3,
        descripcion: "Purificadora y resistente",
        category: "plantas",
        img: "https://res.cloudinary.com/dfzxicmrq/image/upload/v1697878558/pachira_nayifa.avif",
    },
    {
        title: "Ave del Paraiso",
        price: 3000,
        stock: 3,
        descripcion: "Decoradora y resistente",
        category: "plantas",
        img: "https://res.cloudinary.com/dfzxicmrq/image/upload/v1697878682/paraiso_w0jrav.avif",
    },
    {
        title: "Olivo",
        price: 3000,
        stock: 3,
        descripcion: "Resistente y hermoso",
        category: "plantas",
        img: "https://res.cloudinary.com/dfzxicmrq/image/upload/v1697878937/olivo_hjbi06.avif",
    },
    {
        title: "Monstera",
        price: 3000,
        stock: 3,
        descripcion: "Se adapta a cualquier ambiente",
        category: "plantas",
        img: "https://res.cloudinary.com/dfzxicmrq/image/upload/v1697878944/monstera_zim88t.avif",
    },

    {
        title: "Maceta Amsterdam",
        price: 1500,
        stock: 3,
        descripcion: "Materiales 100% reciclados",
        category: "macetas",
        img: "https://res.cloudinary.com/dfzxicmrq/image/upload/v1697878957/macetaAmsterdam_lbnel5.avif",
    },
    {
        title: "Maceta Kenia",
        price: 1500,
        stock: 3,
        descripcion: "Cerámica blanca y brillante",
        category: "macetas",
        img: "https://res.cloudinary.com/dfzxicmrq/image/upload/v1697878960/macetaKenia_swknjc.avif",
    },
    {
        title: "Maceta Toronto",
        price: 1500,
        stock: 3,
        descripcion: "Materiales 100% reciclados",
        category: "macetas",
        img: "https://res.cloudinary.com/dfzxicmrq/image/upload/v1697878963/macetaToronto_wvbzcs.avif",
    },
]                 